[package]
edition = "2021"
name = "native-utils"
version = "0.0.0"

[workspace]
members = ["migration"]

[features]
default = []
napi = ["dep:napi", "dep:napi-derive"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
async-trait = "0.1.75"
cfg-if = "1.0.0"
chrono = "0.4.31"
cuid2 = "0.1.2"
derive_more = "0.99.17"
jsonschema = "0.17.1"
once_cell = "1.19.0"
parse-display = "0.8.2"
rand = "0.8.5"
schemars = { version = "0.8.16", features = ["chrono"] }
sea-orm = { version = "0.12.10", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.52"
tokio = { version = "1.35.1", features = ["full"] }
utoipa = "4.1.0"

# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.14.1", default-features = false, features = ["napi6", "tokio_rt"], optional = true }
napi-derive = { version = "2.14.5", optional = true }
basen = "0.1.0"

[dev-dependencies]
pretty_assertions = "1.4.0"

[build-dependencies]
napi-build = "2.1.0"

[profile.release]
lto = true
